### ISSUE TITLE
Error Message: rich_text[0].text.content.length should be ≤ `2000`, instead was `4218`

### ISSUE THREAD

**Issue by janduplessis883** [markomanninen/md2notion#4]
### md2notion
I am working on report creation using **CrewAI**, and want to dynamically write reports to **Notion Tasks** created by my LLM.
I had an issue writing the LLM markdown output in a readable format to Notion - and I found **md2notion** - brilliant package, thank you.

### Error: text.content.length should be ≤ `2000`, instead was `4218`
**Can this be handled within your package** or do I have to batch my markdown before passing to md2notion to overcome the 2000 character limit on the Notion API?

**Here is the full error message.**
```
Traceback (most recent call last):
  File "/Users/janduplessis/code/janduplessis883/notion-agent/new_task.py", line 378, in <module>
    notion_page_url = md2notionpage(markdown_text, title, parent_page_id)
  File "/Users/janduplessis/.pyenv/versions/lewagon/lib/python3.10/site-packages/md2notionpage/core.py", line 595, in create_notion_page_from_md
    notion.blocks.children.append(
  File "/Users/janduplessis/.pyenv/versions/lewagon/lib/python3.10/site-packages/notion_client/api_endpoints.py", line 23, in append
    return self.parent.request(
  File "/Users/janduplessis/.pyenv/versions/lewagon/lib/python3.10/site-packages/notion_client/client.py", line 194, in request
    return self._parse_response(response)
  File "/Users/janduplessis/.pyenv/versions/lewagon/lib/python3.10/site-packages/notion_client/client.py", line 126, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: body failed validation: body.children[0].code.rich_text[0].text.content.length should be ≤ `2000`, instead was `4218`.
make: *** [newtask] Error 1
```

Your help is much appreciated.
Thank you 😀
janduplessis883

**Comment by Hari19hk** [comment]
@markomanninen  can i work on this issue? I have been using notion API recently and manually batching md is annoying so i would like to contribute to this.

**Comment by markomanninen** [comment]
@Hari19hk Yes, please, let me review PR then, thanks.

**Comment by markomanninen** [comment]
Resolved on #9
